# Generated by Django 3.2.19 on 2023-09-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230907_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='bak',
            name='work',
            field=models.CharField(choices=[('HB', 'hangbu'), ('HBM', 'hangbumem'), ('IB', 'ibbu'), ('IBM', 'ibbumem'), ('GB', 'gambu'), ('GBM', 'gambumem')], max_length=3, null=True),
        ),
    ]
