# Generated by Django 3.2.19 on 2023-09-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bak_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bak',
            name='work',
            field=models.CharField(choices=[('NN', 'none'), ('HB', 'hangbu'), ('HBM', 'hangbumem'), ('IB', 'ibbu'), ('IBM', 'ibbumem'), ('GB', 'gambu'), ('GBM', 'gambumem')], max_length=3, null=True),
        ),
    ]
